[package]
name = "elnafo-frontend"
version = "0.1.0"
edition = "2021"
authors = ["L-Nafaryus <l.nafaryus@elnafo.ru>"]

[build-dependencies]
ignore = "0.4.22"
npm_rs = "1.0.0"

[dependencies]
askama = { version = "0.12.1", features = ["with-axum"] }
askama_axum = "0.4.0"
rust-embed = "8.3.0"
