[package]
name = "elnafo"
version = "0.1.0"
edition = "2021"
authors = ["L-Nafaryus <l.nafaryus@elnafo.ru"]

[[bin]]
name = "elnafo"
path = "src/main.rs"

[dependencies]
diesel = { version = "2.1.4", features = ["postgres"] }
db = { path = "../db" }
